name: Test

on: 
  push: 
   branches: [ dev ]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
       path: ~/.npm
       key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
        ${{ runner.os }}-node-
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./pegasus/client/
        build: npm run build
        start: npm start
